### PR TITLE
Desktop dimension chooser updates

### PR DESCRIPTION
**Pull request by amcclain**
- Config to suppress display of toolbar
- Fix bug where Add Grouping button displayed when maxDepth = 1

### CODE REVIEW

**Comment by lbwexler** [comment]
@amcclain  -- should we just kill this one?   Don't think we have any usages where maxDepth=1.

**Comment by amcclain** [comment]
Yes I think we could - this hasn't been an issue in practice and I don't expect it will become one.

**Comment by lbwexler** [comment]
Closing this -- as discussed with Anselm, we have not actually seen a use for maxDepth=1

**Comment by lbwexler** [comment]
And to be clear, we are trying to avoid any destabilizing changes in Hoist Sencha

**Pull request closed without merging**
